version: "3"

services:
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=chukky
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=mongo_first

  redis:
    image: redis:6.2.1-alpine3.13

  nginx:
    image: nginx:stable-alpine
    volumes:
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3000:80
