version: "3"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - $PWD:/app
      - $PWD/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_IP=mongo
      - MONGO_USER=chukky
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:

  nginx:
    ports:
      - 3000:80
